(()=>{'use strict';
const C=window.MATICA_CONFIG||{},A='';const $=s=>document.querySelector(s);const stage=$('#stage');
const scenes=[
{kind:'video',name:'La sala dei numeri',title:'Chi sono i numeri primi?',desc:'Scopri il mondo dei numeri primi, la loro definizione e il Teorema fondamentale dell’aritmetica.',bg:'atrio-primi.png',preview:'panorama-primi.jpg',video:'video1'},
{kind:'pano',name:'Il regno dei numeri',title:'Esplora i numeri',bg:'panorama-primi.jpg',group:'primes',quiz:'prime'},
{kind:'video',name:'La Grecia di Euclide',title:'I primi sono infiniti?',desc:'Entra nella Grecia antica e ascolta la dimostrazione di Euclide.',bg:'scena-euclide.jpg',preview:'panorama-euclide.jpg',video:'video2'},
{kind:'pano',name:'La biblioteca di Euclide',title:'Sulle tracce di Euclide',bg:'panorama-euclide.jpg',group:'euclid'},
{kind:'video',name:'Il castello di Arsinoe',title:'Come troviamo i numeri primi?',desc:'Dalla corte tolemaica al crivello di Eratostene: scopri un metodo per trovare tutti i primi fino a un numero scelto.',bg:'scena-arsinoe.jpg',preview:'panorama-eratostene.jpg',video:'video3'},
{kind:'pano',name:'La sala di Eratostene',title:'La selezione dei numeri',bg:'panorama-eratostene.jpg',group:'eratosthenes'},
{kind:'embed',name:'Il crivello interattivo'},
{kind:'video',name:'Il mondo delle relazioni',title:'Multipli e divisori',desc:'Ogni numero ha legami con altri numeri. Scopri che cosa significa essere multiplo o divisore.',bg:'scena-divisori.jpg',preview:'panorama-divisori.jpg',video:'video6'},
{kind:'pano',name:'La stanza dei numeri parlanti',title:'Ascolta le relazioni',bg:'panorama-divisori.jpg',group:'divisors',quiz:'divisor'},
{kind:'final',name:'La prova finale'}];
let index=0, watched={},quizPassed={},viewer=null,questionState=null,sound=false,changing=false; const visited=new Set();
const primeList=[2,3,5,7,11,13,17,19,23,29];
const prime=n=>n>1&&Array.from({length:Math.floor(Math.sqrt(n))-1},(_,i)=>i+2).every(d=>n%d!==0);
function factor(n){let a=[];for(let d=2;d<=n;d++)while(n%d===0){a.push(d);n/=d}return a}
function normFactors(s){const v=s.trim().replaceAll('×','x').replaceAll('·','x').replaceAll('*','x').replace(/\s/g,'').split('x').map(Number);return v.length&&v.every(Number.isInteger)?v.sort((a,b)=>a-b):[]}
function shuffle(a){let b=a.slice();for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function btn(label,fn,cls='btn'){const e=document.createElement('button');e.className=cls;e.textContent=label;e.addEventListener('click',fn);return e}
function el(tag,cls,html){const v=document.createElement(tag);if(cls)v.className=cls;if(html!==undefined)v.innerHTML=html;return v}
function modal(html,{wide=false,close=null}={}){const mb=$('.modalbox');mb.classList.toggle('videoMode',wide);$('#modalBody').innerHTML=html;$('#modal').classList.remove('hide');$('#closeModal').onclick=()=>{hideModal();close?.()}};
function hideModal(){$('#modal').classList.add('hide');$('#modalBody').innerHTML='';}
function escapeH(s){return String(s).replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]))}
function videoId(v){if(!v)return '';if(/^[a-zA-Z0-9_-]{11}$/.test(v))return v;try{const u=new URL(v);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1);if(u.hostname.includes('youtube.com'))return u.searchParams.get('v')||u.pathname.split('/').pop();}catch{}return ''}
function playVideo(key,done){const id=videoId(C[key]);const title={video1:'Definizione e Teorema fondamentale',video2:'I numeri primi sono infiniti',video3:'Come si trovano i numeri primi',video4:'Eratostene: approfondimento',video5:'Secondo filmato di Eratostene',video6:'Multipli e divisori'}[key]||'Video';let body=id?`<h2>${title}</h2><iframe class="video" src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?rel=0" title="${title}" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe><p>Chiudi con ✕ per tornare all’avventura.</p>`:`<div class="videoFallback"><h2>${title}</h2><p>Questo link YouTube non è ancora stato inserito nel file <code>config.js</code>.</p><p>In questa versione di montaggio puoi comunque esplorare la stanza successiva.</p></div>`;
modal(body,{wide:true,close:()=>{if(done){watched[key]=true;render()}}});}
function travel(next){if(changing||next<0||next>=scenes.length)return;changing=true;if(viewer){viewer.dispose();viewer=null}const t=$('#transition');t.classList.remove('hide');setTimeout(()=>{index=next;render()},1220);setTimeout(()=>{t.classList.add('hide');changing=false},2280)}
function render(){visited.add(index);let s=scenes[index];$('#stageLabel').textContent=s.name;$('#progress').textContent=`✦ ${visited.size} / ${scenes.length}`;stage.innerHTML='';if(s.kind==='video')renderVideoScene(s);else if(s.kind==='pano')renderPanoScene(s);else if(s.kind==='embed')renderEmbed();else renderFinal();}
function renderVideoScene(s){let root=el('section','scene');root.style.backgroundImage=`url("${A+s.bg}")`;root.innerHTML=`<div class="intro"><h1>${escapeH(s.title)}</h1><p>${escapeH(s.desc)}</p><p><b>Obiettivi:</b> riconoscere primi e composti, comprendere la scomposizione unica in fattori primi e le relazioni tra multipli e divisori.</p></div>`;let wrap=el('div','portal-wrap'),isWatched=!!watched[s.video],p=el('button','portal');p.setAttribute('aria-label',isWatched?'Attraversa il portale':'Apri la lezione video');p.innerHTML=`<span class="preview" style="background-image:url('${A+(isWatched?s.preview:s.bg)}')"></span><span class="playmark">${isWatched?'✧':'▶'}</span>`;p.onclick=()=>isWatched?travel(index+1):playVideo(s.video,true);wrap.append(p,el('div','portal-label',isWatched?'✦ Attraversa il portale • entra nella stanza':'▶ Tocca il cerchio per guardare la lezione'));root.append(wrap);let aside=el('div','side-actions');aside.append(el('div','notice',isWatched?'Hai aperto la lezione. Ora il portale mostra la stanza successiva.':'Guarda il video, chiudilo con ✕ e torna al cerchio trasformato in portale.'));aside.append(btn('Riapri il video',()=>playVideo(s.video,true),'btn alt'));root.append(aside);stage.append(root)}
const factText=n=>n<2?'Non ho una scomposizione in fattori primi.':`Sono ${factor(n).join(' × ')}.`;
function makeMarkers(group){if(group==='primes'){
const p=[1,2,3,5,7,11,13,17,19,23],c=[4,6,8,9,10,15,16,18,20];return [...p.map((n,i)=>({label:n,lon:-165+i*34,lat:5+(i%3)*-11,type:'prime',text:n===1?'Sono 1: non sono né primo né composto.':n===2?'Sono 2: l’unico numero primo pari.':n===3?'Sono 3: il più piccolo primo dispari.':`Sono ${n}: sono divisibile soltanto per 1 e per me stesso.`})),...c.map((n,i)=>({label:n,lon:-152+i*38,lat:-24-(i%2)*12,type:'comp',text:`Sono ${n}: ${factText(n)} Sono composto perché ho più di due divisori positivi.`}))]}
if(group==='euclid')return [
{label:'✦',lon:-56,lat:3,text:'Euclide scrisse gli Elementi. Nel libro IX si trova una dimostrazione dell’infinità dei numeri primi.'},
{label:'∞',lon:-20,lat:0,text:'I numeri primi sono infiniti: nessun elenco finito può contenerli tutti.'},
{label:'P',lon:24,lat:3,text:'Se supponiamo di conoscere tutti i primi e consideriamo il loro prodotto più 1, otteniamo un numero non divisibile per nessuno dei primi dell’elenco.'},
{label:'?',lon:64,lat:2,text:'Quel nuovo numero può essere primo oppure composto. Nel secondo caso, ha almeno un fattore primo non presente nell’elenco: l’ipotesi iniziale è impossibile.'}];
if(group==='eratosthenes')return [
{label:'2',lon:-62,lat:0,text:'Comincio dal 2 e cancello tutti i suoi multipli maggiori di 2.'},
{label:'3',lon:-25,lat:0,text:'Il primo numero non cancellato dopo il 2 è il 3. Cancello i suoi multipli maggiori di 3.'},
{label:'5',lon:20,lat:0,text:'Proseguo con il primo numero non cancellato, senza cancellare il numero stesso.'},
{label:'√',lon:58,lat:0,text:'Per trovare i primi fino a N basta eliminare i multipli dei primi non superiori a √N.'}];
return [
{label:20,lon:-92,lat:8,text:'Sono 20. Sono multiplo di 2, 4, 5 e 10 (e anche di 1 e 20).'},
{label:6,lon:-55,lat:7,text:'Sono 6: sono divisore di 12 e multiplo di 1, 2 e 3.'},
{label:12,lon:-16,lat:10,text:'Sono 12: sono multiplo di 3 e 4; 2, 3, 4 e 6 sono miei divisori.'},
{label:15,lon:25,lat:9,text:'Sono 15: 3 e 5 sono miei divisori e io sono multiplo di entrambi.'},
{label:24,lon:68,lat:8,text:'Sono 24: sono multiplo di 6, 8 e 12. Sono divisore di 48.'},
{label:1,lon:110,lat:8,text:'Sono 1: divisore di ogni numero naturale positivo, ma non sono primo né composto.'},
{label:9,lon:155,lat:9,text:'Sono 9: sono multiplo di 3 e divisore di 18, 27 e 36.'}];}
class Pano{constructor(node,file){this.node=node;this.node.innerHTML='';this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(72,node.clientWidth/node.clientHeight,1,1100);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.setSize(node.clientWidth,node.clientHeight);node.append(this.renderer.domElement);this.lon=0;this.lat=0;this.drag=false;this.fov=72;this.markerObjects=[];this.listeners=[];let geo=new THREE.SphereGeometry(500,64,44);geo.scale(-1,1,1);this.mat=new THREE.MeshBasicMaterial({color:0x101835});this.sphere=new THREE.Mesh(geo,this.mat);this.scene.add(this.sphere);new THREE.TextureLoader().load(A+file,tex=>{if(this.dead){tex.dispose();return}this.mat.map=tex;this.mat.needsUpdate=true},undefined,()=>{this.node.insertAdjacentHTML('beforeend','<p>Immagine panoramica non caricata.</p>')});this.install();this.tick()}
listen(node,event,fn,opts){node.addEventListener(event,fn,opts);this.listeners.push([node,event,fn,opts])}
install(){const c=this.node;let old=null;this.listen(c,'pointerdown',e=>{if(e.target.closest('button'))return;this.drag=true;old=[e.clientX,e.clientY];c.classList.add('dragging');c.setPointerCapture(e.pointerId)});this.listen(c,'pointermove',e=>{if(!this.drag||!old)return;let dx=e.clientX-old[0],dy=e.clientY-old[1];this.lon-=dx*.13;this.lat=Math.max(-60,Math.min(60,this.lat+dy*.13));old=[e.clientX,e.clientY]});this.listen(c,'pointerup',()=>{this.drag=false;old=null;c.classList.remove('dragging')});this.listen(c,'wheel',e=>{e.preventDefault();this.fov=Math.max(32,Math.min(98,this.fov+e.deltaY*.05));this.camera.fov=this.fov;this.camera.updateProjectionMatrix()},{passive:false});this.ro=new ResizeObserver(()=>{if(this.dead)return;let w=c.clientWidth,h=c.clientHeight;if(w&&h){this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h)}});this.ro.observe(c)}
markers(items,onClick){this.markerObjects=items.map((item)=>{const b=btn(String(item.label),()=>onClick(item),'pano-marker '+(item.type||'info'));b.setAttribute('aria-label','Esplora: '+item.label);this.node.append(b);return {item,b}})}
tick(){if(this.dead)return;let phi=THREE.MathUtils.degToRad(90-this.lat),theta=THREE.MathUtils.degToRad(this.lon);this.camera.lookAt(new THREE.Vector3(500*Math.sin(phi)*Math.cos(theta),500*Math.cos(phi),500*Math.sin(phi)*Math.sin(theta)));this.camera.updateMatrixWorld();let w=this.node.clientWidth,h=this.node.clientHeight;for(const {item,b} of this.markerObjects){let p=THREE.MathUtils.degToRad(90-(item.lat||0)),t=THREE.MathUtils.degToRad(item.lon);const v=new THREE.Vector3(490*Math.sin(p)*Math.cos(t),490*Math.cos(p),490*Math.sin(p)*Math.sin(t));const cam=v.clone().applyMatrix4(this.camera.matrixWorldInverse);if(cam.z>=0){b.style.display='none';continue}v.project(this.camera);if(Math.abs(v.x)>1.07||Math.abs(v.y)>1.08){b.style.display='none';continue}b.style.display='block';b.style.left=((v.x+1)*.5*w)+'px';b.style.top=((-v.y+1)*.5*h)+'px'}this.renderer.render(this.scene,this.camera);this.raf=requestAnimationFrame(()=>this.tick())}
zoom(d){this.fov=Math.max(32,Math.min(98,this.fov+d));this.camera.fov=this.fov;this.camera.updateProjectionMatrix()}
dispose(){this.dead=true;cancelAnimationFrame(this.raf);this.ro?.disconnect();this.listeners.forEach(([n,e,f,o])=>n.removeEventListener(e,f,o));this.mat.map?.dispose();this.mat.dispose();this.sphere.geometry.dispose();this.renderer.dispose();this.renderer.domElement.remove()}}
function renderPanoScene(s){const node=el('div','pano');stage.append(node);if(!window.THREE){node.innerHTML=`<div class="scene" style="background-image:url('${A+s.bg}')"><div class="intro"><h2>Impossibile caricare il visore 360°</h2><p>Serve la libreria Three.js e una connessione a Internet.</p></div></div>`;return}viewer=new Pano(node,s.bg);const hint=el('div','pano-hint','Trascina per esplorare · scorri/pizzica per zoomare · clicca i simboli');node.append(hint);setTimeout(()=>hint.remove(),7000);
const markers=makeMarkers(s.group);const panel=el('div','pano-panel',`<h2>${escapeH(s.title)}</h2><p id="factInfo">Sposta lo sguardo e scopri gli hotspot nascosti nella scena.</p>`);node.append(panel);viewer.markers(markers,item=>{const p=$('#factInfo');if(p)p.textContent=item.text});const controls=el('div','pano-controls');node.append(controls);controls.append(btn('＋ Zoom',()=>viewer.zoom(-10),'mini'),btn('－ Zoom',()=>viewer.zoom(10),'mini'));
if(s.group==='eratosthenes'){controls.append(btn('▶ Video Eratostene',()=>playVideo('video4'),'mini'));if(C.video5)controls.append(btn('▶ Secondo video',()=>playVideo('video5'),'mini'))}
if(s.quiz){controls.append(btn(quizPassed[index]?'✓ Quiz superato · prosegui':'✦ Affronta 5 quesiti',()=>quizPassed[index]?travel(index+1):startQuiz(s.quiz,5,3,()=>{quizPassed[index]=true;travel(index+1)}),'btn'));}else controls.append(btn('✧ Attraversa il passaggio',()=>travel(index+1),'btn'));
}
function renderEmbed(){let root=el('div','scene');root.innerHTML=`<div class="intro" style="top:63px;max-width:none"><h2>Il crivello di Eratostene</h2><p>Sperimenta: quali numeri restano quando elimini progressivamente i multipli?</p></div><iframe id="crivello" class="embed embedScene" title="Crivello Matica" loading="eager" src="${escapeH(C.crivello)}"></iframe>`;let bar=el('div','embedToolbar');bar.append(btn('Apri in un’altra scheda',()=>window.open(C.crivello,'_blank','noopener'),'btn alt'));bar.append(btn('✧ Ho esplorato il crivello · prosegui',()=>travel(index+1)));root.append(bar);stage.append(root)}
function createPrimeQuiz(){const nums=shuffle(Array.from({length:30},(_,i)=>i+1));let selected=nums.slice(0,5);if(!selected.includes(1)&&Math.random()<.5)selected[0]=1;return selected.map((n,i)=>{if(n===1||prime(n)||i%2===0)return {type:'choice',text:`Il numero ${n} è…`,choices:['Primo','Composto','Né primo né composto'],correct:n===1?2:prime(n)?0:1,explanation:n===1?'1 ha un solo divisore positivo.':prime(n)?`${n} ha esattamente due divisori positivi.`:`${n} = ${factor(n).join(' × ')}.`};return {type:'factors',text:`Scomponi ${n} in fattori primi. Scrivi per esempio 2×3×3.`,n,explanation:`${n} = ${factor(n).join(' × ')}. L’ordine dei fattori non conta.`}})}
function createDivQuiz(){const pool=[];for(let a=2;a<=12;a++)for(let b=2;b<=12;b++){pool.push({type:'choice',text:`${a} è divisore di ${a*b}?`,choices:['Sì','No'],correct:0,explanation:`${a*b} = ${a} × ${b}.`});pool.push({type:'choice',text:`${a*b} è multiplo di ${a}?`,choices:['Sì','No'],correct:0,explanation:`${a*b} = ${a} × ${b}.`});let n=a*b+1;pool.push({type:'choice',text:`${a} è divisore di ${n}?`,choices:['Sì','No'],correct:1,explanation:`${n} diviso ${a} non dà un quoziente intero.`})}return shuffle(pool).slice(0,5)}
// Bank of 50+ independently constructed, editable questions; options randomized at runtime.
function finalBank(){let q=[
['Quale definizione descrive un numero primo?',['Un naturale maggiore di 1 con esattamente due divisori positivi','Un numero divisibile per 1 e per 2','Un naturale con un solo divisore'],0,'La definizione richiede esattamente due divisori: 1 e se stesso.'],
['Il numero 1 è…',['Primo','Composto','Né primo né composto'],2,'1 possiede un unico divisore positivo.'],
['Qual è l’unico numero primo pari?',['2','4','6'],0,'Ogni numero pari maggiore di 2 è divisibile anche per 2.'],
['Quale enunciato esprime il Teorema fondamentale dell’aritmetica?',['Ogni naturale maggiore di 1 è primo oppure si scrive come prodotto di primi, in modo unico a meno dell’ordine','Ogni naturale è somma di due primi','Ogni numero primo è pari'],0,'La scomposizione in primi esiste ed è unica, salvo l’ordine dei fattori.'],
['Quanti numeri primi esistono?',['Infiniti','Esattamente cento','Un numero finito ancora sconosciuto'],0,'Euclide dimostrò che non può esistere un elenco completo e finito di tutti i primi.'],
['Nel crivello di Eratostene, dopo aver considerato il 2…',['Elimino i suoi multipli maggiori di 2','Elimino il 2','Elimino tutti i dispari'],0,'Il 2 deve restare: è un numero primo.'],
['Se a è divisore di b, allora…',['b è multiplo di a','a è necessariamente maggiore di b','b è sempre primo'],0,'La relazione tra divisore e multiplo è reciproca.'],
['Quale affermazione è corretta?',['Ogni naturale positivo è multiplo di 1','1 è primo','Ogni dispari è primo'],0,'Qualunque n è 1 × n.'],
['Un numero composto maggiore di 1 è…',['Un numero con più di due divisori positivi','Un numero dispari','Un numero che termina in 0'],0,'I composti possiedono altri divisori oltre a 1 e a se stessi.']
].map(([text,choices,correct,explanation])=>({type:'choice',text,choices,correct,explanation}));
for(let n of [4,6,8,9,10,12,14,15,16,18,20,21,24,25,27,28,30,32,36,40,42,45,48,49,50,54,60,63,70,72,75,81,84,90,96,100])q.push({type:'factors',text:`Scomponi ${n} in fattori primi.`,n,explanation:`${n} = ${factor(n).join(' × ')}.`});
for(let n of [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,51,57,61,67,71,77,79,83,89,91,97])q.push({type:'choice',text:`Il numero ${n} è primo o composto?`,choices:['Primo','Composto'],correct:prime(n)?0:1,explanation:prime(n)?`${n} è primo.`:`${n} = ${factor(n).join(' × ')}.`});
for(let [a,b] of [[2,18],[3,21],[4,28],[5,45],[6,42],[7,49],[8,72],[9,81],[10,100],[11,99],[12,108],[4,30],[5,32],[7,48],[9,50],[8,54]])q.push({type:'choice',text:`${a} è divisore di ${b}?`,choices:['Sì','No'],correct:b%a===0?0:1,explanation:b%a===0?`${b} = ${a} × ${b/a}.`:`La divisione di ${b} per ${a} non è esatta.`});
for(let [a,b] of [[18,3],[25,5],[40,10],[48,6],[64,8],[72,9],[81,3],[84,7],[91,13],[50,6],[33,5],[42,8]])q.push({type:'choice',text:`${a} è multiplo di ${b}?`,choices:['Sì','No'],correct:a%b===0?0:1,explanation:a%b===0?`${a} = ${b} × ${a/b}.`:`${a} diviso ${b} non è un intero.`});return q;}
function finalQuestions(){let bank=shuffle(finalBank()),out=[];for(let typ of ['factors','choice']){let take=bank.filter(q=>q.type===typ).slice(0,typ==='factors'?5:10);out.push(...take)}return shuffle(out).map(q=>q.type!=='choice'?q:(()=>{let c=shuffle(q.choices.map((v,i)=>({v,good:i===q.correct})));return {...q,choices:c.map(x=>x.v),correct:c.findIndex(x=>x.good)}})())}
function startQuiz(type,total,threshold,success){const qs=type==='prime'?createPrimeQuiz():type==='divisor'?createDivQuiz():finalQuestions();questionState={qs:qs.slice(0,total),i:0,score:0,answered:false,threshold,success,type};renderQ()}
function checkAnswer(q,value){if(q.type==='factors'){const ar=normFactors(value);return ar.length===factor(q.n).length&&ar.every((x,i)=>x===factor(q.n)[i])}return Number(value)===q.correct}
function renderQ(){let S=questionState;if(!S)return;if(S.i>=S.qs.length)return endQuiz();const q=S.qs[S.i];let html=`<div class="qcard"><div class="qcount">Domanda ${S.i+1}/${S.qs.length} · Risposte corrette: ${S.score}</div><h2>${escapeH(q.text)}</h2><div id="qAnswers" class="answers">${q.type==='factors'?'<input id="factorAnswer" type="text" aria-label="Scomposizione in fattori primi" placeholder="es. 2 × 2 × 3" autocomplete="off">':q.choices.map((c,i)=>`<button class="answer" data-choice="${i}">${escapeH(c)}</button>`).join('')}</div><p id="feedback" class="feedback" aria-live="polite">Ragiona con calma. Ogni domanda vale un punto.</p><button id="check" class="btn" disabled>Conferma risposta</button><button id="nextQ" class="btn alt hide">${S.i+1===S.qs.length?'Vedi risultato':'Domanda successiva →'}</button></div>`;modal(html);let choice=null;$('#qAnswers').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{choice=Number(b.dataset.choice);$('#qAnswers').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));$('#check').disabled=false});if(q.type==='factors'){const input=$('#factorAnswer');input.addEventListener('input',()=>$('#check').disabled=!input.value.trim());input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!$('#check').disabled)$('#check').click()})}
$('#check').onclick=()=>{let val=q.type==='factors'?$('#factorAnswer').value:choice;let correct=checkAnswer(q,val);if(correct)S.score++;$('#feedback').textContent=(correct?'✓ Risposta corretta. ':'✕ Non esatta. ')+q.explanation;$('#qAnswers').querySelectorAll('button,input').forEach(b=>b.disabled=true);$('#check').classList.add('hide');$('#nextQ').classList.remove('hide');$('#closeModal').disabled=true;};$('#nextQ').onclick=()=>{S.i++;hideModal();$('#closeModal').disabled=false;renderQ()}}
function endQuiz(){const s=questionState;$('#closeModal').disabled=false;let passed=s.score>=s.threshold;modal(`<div class="qcard"><h2>${passed?'✦ Portale sbloccato!':'✧ Puoi riprovare'}</h2><p>Hai ottenuto <strong>${s.score}/${s.qs.length}</strong>. Soglia richiesta: <strong>${s.threshold}/${s.qs.length}</strong>.</p><p>${passed?'Il tuo viaggio può continuare.':'Torna a esplorare, poi ritenta: saranno estratte nuove domande.'}</p><button id="quizDone" class="btn">${passed?'Prosegui →':'Torna alla stanza'}</button></div>`);$('#quizDone').onclick=()=>{hideModal();questionState=null;if(passed)s.success()};}
function renderFinal(){let root=el('div','scene');root.style.backgroundImage=`url('${A}atrio-primi.png')`;root.innerHTML='<div class="intro"><h1>Il portale della conoscenza</h1><p>Hai esplorato il mondo dei numeri primi, incontrato Euclide, sperimentato il crivello e imparato le relazioni tra multipli e divisori.</p><p><b>Prova conclusiva:</b> 15 quesiti casuali, uno alla volta. Con almeno 9 punti ricevi l’attestato.</p></div>';const wrap=el('div','portal-wrap');wrap.append(btn('✦ Inizia la prova finale (15 domande)',()=>startQuiz('final',15,9,()=>{hideModal();showCert(questionState?.score??lastFinalScore)})));root.append(wrap);stage.append(root);}
let lastFinalScore=0; // Used to preserve the result once the quiz modal closes.
// Patch: keep final score before invoking certificate callback, with an explicit score argument.
const originalEnd=endQuiz;
endQuiz=function(){let s=questionState;if(s?.type==='final')lastFinalScore=s.score;originalEnd()};
function showCert(score){score=Number.isInteger(score)?score:lastFinalScore;if(score<9){render();return}let level=score===15?'ECCELLENTE':score>=13?'OTTIMO':score>=11?'BUONO':'BASE';stage.innerHTML=`<div id="finish"><div class="certwrap"><div class="certificate"><div style="font-size:28px">✦ MATICA ✦</div><h1>Attestato del viaggio<br>dei numeri primi</h1><p>Si conferisce a</p><input id="studentName" maxlength="65" placeholder="Inserisci il tuo nome" aria-label="Nome dello studente"><h2>${level}</h2><p>per aver completato il percorso interattivo e superato la prova finale con</p><div style="font-size:42px;font-weight:bold">${score} / 15</div><p>Con Mate e Carl • Il viaggio nella matematica</p><small>© Claudia Bartoli — attestato di completamento del percorso didattico</small></div><div class="certButtons"><button id="printCert" class="btn">Stampa / Salva PDF</button><button id="retryFinal" class="btn alt">Riprova il test</button></div></div></div>`;$('#printCert').onclick=()=>{if(!$('#studentName').value.trim()){alert('Inserisci prima il tuo nome.');$('#studentName').focus();return}window.print()};$('#retryFinal').onclick=()=>{index=9;render()}}
$('#privacyBtn').onclick=()=>modal(`<h2>Privacy</h2><p>Questo progetto didattico non richiede registrazione, non dispone di un backend proprietario e non invia al gestore i risultati dei quiz o il nome inserito nell’attestato.</p><p>I video incorporati da YouTube (modalità youtube-nocookie), l’eventuale libreria Three.js caricata da CDN e la risorsa esterna del crivello possono effettuare connessioni ai rispettivi servizi, soggetti alle loro informative. Prima di incorporare il crivello verificare anche la relativa informativa.</p><p>Per informazioni: <a href="mailto:${escapeH(C.email)}">${escapeH(C.email)}</a>.</p><p>© Claudia Bartoli. Riproduzione e distribuzione dei materiali protetti non autorizzate, salvo eccezioni previste dalla legge e diritti di terzi.</p>`);
$('#helpBtn').onclick=()=>modal('<h2>Come si gioca</h2><p>1. In ciascun atrio premi il cerchio per aprire la videolezione. Quando chiudi il video, il cerchio diventa un portale verso la scena successiva.</p><p>2. Nei panorami trascina per guardarti attorno e clicca sui numeri o sui simboli luminosi. Su smartphone trascina con un dito.</p><p>3. Supera i due mini quiz con almeno 3 risposte esatte su 5. Nel crivello esplora la risorsa e premi Prosegui.</p><p>4. Rispondi a 15 quesiti finali: per ottenere l’attestato servono almeno 9 punti.</p><p>Le scomposizioni si scrivono ad esempio 2×2×3; l’ordine dei fattori non conta.</p>');
$('#restartBtn').onclick=()=>{if(confirm('Vuoi ricominciare il viaggio dall’inizio?')){if(viewer){viewer.dispose();viewer=null}index=0;watched={};quizPassed={};visited.clear();hideModal();render()}};
$('#audioBtn').onclick=()=>modal('<p>La colonna sonora non è inclusa in questa versione. Le videolezioni conservano i propri controlli audio.</p>');
render();
})();
