(()=>{'use strict';
const C=window.MATICA_CONFIG||{},A='';const $=s=>document.querySelector(s);const stage=$('#stage');
const scenes=[
{kind:'video',name:'La sala dei numeri',title:'Chi sono i numeri primi?',desc:'Scopri il mondo dei numeri primi, la loro definizione e il Teorema fondamentale dell’aritmetica.',bg:'atrio-primi.png',preview:'panorama-primi.jpg',video:'video1'},
{kind:'pano',name:'Il regno dei numeri',title:'Esplora i numeri',bg:'panorama-primi.jpg',group:'primes',quiz:'prime'},
{kind:'video',name:'La Grecia di Euclide',title:'I primi sono infiniti?',desc:'Entra nella Grecia antica e ascolta la dimostrazione di Euclide.',bg:'scena-euclide.jpg',preview:'panorama-euclide.jpg',video:'video2'},
{kind:'pano',name:'La biblioteca di Euclide',title:'Sulle tracce di Euclide',bg:'panorama-euclide.jpg',group:'euclid'},
{kind:'video',name:'Il castello di Arsinoe',title:'Come troviamo i numeri primi?',desc:'Dalla corte tolemaica al crivello di Eratostene: scopri un metodo per trovare tutti i primi fino a un numero scelto.',bg:'scena-arsinoe.jpg',preview:'panorama-eratostene.jpg',video:'video3'},
{kind:'pano',name:'La sala di Eratostene',title:'La selezione dei numeri',bg:'panorama-eratostene.jpg',group:'eratosthenes'},
{kind:'embed',name:'Il crivello interattivo'},
{kind:'video',name:'Il mondo delle relazioni',title:'Multipli e divisori',desc:'Ogni numero ha legami con altri numeri. Scopri che cosa significa essere multiplo o divisore.',bg:'scena-divisori.jpg',preview:'panorama-divisori.jpg',video:'video6'},
{kind:'pano',name:'La stanza dei numeri parlanti',title:'Ascolta le relazioni',bg:'panorama-divisori.jpg',group:'divisors',quiz:'divisor'},
{kind:'final',name:'La prova finale'}];
let index=0, watched={},quizPassed={},viewer=null,questionState=null,sound=false,changing=false; const visited=new Set();
const primeList=[2,3,5,7,11,13,17,19,23,29];
const prime=n=>n>1&&Array.from({length:Math.floor(Math.sqrt(n))-1},(_,i)=>i+2).every(d=>n%d!==0);
function factor(n){let a=[];for(let d=2;d<=n;d++)while(n%d===0){a.push(d);n/=d}return a}
function normFactors(s){const v=s.trim().replaceAll('×','x').replaceAll('·','x').replaceAll('*','x').replace(/\s/g,'').split('x').map(Number);return v.length&&v.every(Number.isInteger)?v.sort((a,b)=>a-b):[]}
function shuffle(a){let b=a.slice();for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function btn(label,fn,cls='btn'){const e=document.createElement('button');e.className=cls;e.textContent=label;e.addEventListener('click',fn);return e}
function el(tag,cls,html){const v=document.createElement(tag);if(cls)v.className=cls;if(html!==undefined)v.innerHTML=html;return v}
function modal(html,{wide=false,close=null}={}){const mb=$('.modalbox');mb.classList.toggle('videoMode',wide);$('#modalBody').innerHTML=html;$('#modal').classList.remove('hide');$('#closeModal').onclick=()=>{hideModal();close?.()}};
function hideModal(){$('#modal').classList.add('hide');$('#modalBody').innerHTML='';}
function escapeH(s){return String(s).replace(/[&<>"']/g,a=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[a]))}
function videoId(v){if(!v)return '';if(/^[a-zA-Z0-9_-]{11}$/.test(v))return v;try{const u=new URL(v);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1);if(u.hostname.includes('youtube.com'))return u.searchParams.get('v')||u.pathname.split('/').pop();}catch{}return ''}
function playVideo(key,done){const id=videoId(C[key]);const title={video1:'Definizione e Teorema fondamentale',video2:'I numeri primi sono infiniti',video3:'Come si trovano i numeri primi',video4:'Eratostene: approfondimento',video5:'Secondo filmato di Eratostene',video6:'Multipli e divisori'}[key]||'Video';let body=id?`<h2>${title}</h2><iframe class="video" src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?rel=0" title="${title}" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe><p>Chiudi con ✕ per tornare all’avventura.</p>`:`<div class="videoFallback"><h2>${title}</h2><p>Questo link YouTube non è ancora stato inserito nel file <code>config.js</code>.</p><p>In questa versione di montaggio puoi comunque esplorare la stanza successiva.</p></div>`;
modal(body,{wide:true,close:()=>{if(done){watched[key]=true;render()}}});}
function travel(next){if(changing||next<0||next>=scenes.length)return;changing=true;if(viewer){viewer.dispose();viewer=null}const t=$('#transition');const flight=t.querySelector('.flight');const scene=scenes[next];flight.style.backgroundImage=scene.bg?`url('${A+scene.bg}')`: `url('${A}atrio-primi.png')`;t.classList.remove('hide');setTimeout(()=>{index=next;render()},1450);setTimeout(()=>{t.classList.add('hide');changing=false},2600)}
function render(){visited.add(index);let s=scenes[index];$('#stageLabel').textContent=s.name;$('#progress').textContent=`✦ ${visited.size} / ${scenes.length}`;stage.innerHTML='';if(s.kind==='video')renderVideoScene(s);else if(s.kind==='pano')renderPanoScene(s);else if(s.kind==='embed')renderEmbed();else renderFinal();}
function renderVideoScene(s){let root=el('section','scene');root.style.backgroundImage=`url("${A+s.bg}")`;
const intro=el('div','intro');intro.innerHTML=`<button class="intro-close" aria-label="Chiudi obiettivi">×</button><h1>${escapeH(s.title)}</h1><p>${escapeH(s.desc)}</p><p><strong>OBIETTIVO:</strong> comprendere i numeri primi, la scomposizione e le relazioni tra multipli e divisori.</p><p><strong>DA SAPERE:</strong> definizione di numero primo ed enunciato del Teorema fondamentale dell’aritmetica.</p>`;
const tab=btn('ⓘ Obiettivi',()=>{intro.classList.remove('hide');tab.classList.add('hide')},'intro-reopen hide');
intro.querySelector('.intro-close').onclick=()=>{intro.classList.add('hide');tab.classList.remove('hide')};root.append(intro,tab);
let wrap=el('div','portal-wrap'),isWatched=!!watched[s.video],p=el('button','portal');p.setAttribute('aria-label',isWatched?'Attraversa il portale':'Apri la lezione video');p.innerHTML=`<span class="preview" style="background-image:url('${A+(isWatched?s.preview:s.bg)}')"></span><span class="playmark">${isWatched?'✧':'▶'}</span>`;p.onclick=()=>isWatched?travel(index+1):playVideo(s.video,true);wrap.append(p,el('div','portal-label',isWatched?'✦ Clicca per entrare nella stanza':'▶ Clicca per guardare la lezione'));root.append(wrap);let aside=el('div','side-actions');aside.append(btn('Riapri il video',()=>playVideo(s.video,true),'btn alt'));root.append(aside);stage.append(root)}

const factText=n=>n<2?'Non ho una scomposizione in fattori primi.':`Sono ${factor(n).join(' × ')}.`;
// Hotspots use normalized texture coordinates, shared with the panorama itself.
function region(label,x,y,w,h,text,type='numberhit',action=null){return {label:String(label),u:x,v:y,uw:w,vh:h,text,type,action}}
function makeMarkers(group){
if(group==='primes'){
const boxes=[[1,722,460,55,76],[2,455,443,65,84],[3,514,443,60,79],[5,568,444,50,72],[7,478,374,48,63],[11,530,381,48,50],[13,475,318,40,42],[17,523,325,44,45],[19,564,342,42,44],[23,584,386,50,48],[4,870,384,40,46],[6,912,369,44,54],[8,958,369,44,54],[9,1002,379,43,62],[10,897,420,48,44],[12,951,418,56,48],[15,870,471,47,51],[16,918,470,47,52],[18,970,474,49,60],[20,1027,475,66,60]];
return boxes.map(([n,x,y,w,h])=>region(n,x/1456,y/720,w/1456,h/720,n===1?'Sono 1: non sono né primo né composto. Ho un solo divisore positivo.':prime(n)?`Sono ${n}: sono primo! Ho esattamente due divisori positivi, 1 e ${n}.`:`Sono ${n}: sono composto! ${n} = ${factor(n).join(' × ')}. Ho più di due divisori positivi.`));
}
if(group==='euclid')return [
region('Euclide',.50,.61,.17,.34,'Euclide scrisse gli Elementi. Nel libro IX si trova una dimostrazione dell’infinità dei numeri primi.'),
region('La dimostrazione',.48,.84,.18,.14,'I numeri primi sono infiniti. Se supponiamo di averli elencati tutti, il loro prodotto più 1 non è divisibile per nessuno dei primi dell’elenco. È primo oppure ha un fattore primo fuori dall’elenco: in entrambi i casi, l’elenco non era completo.'),
region('Passaggio segreto per il castello di Arsinoe',.749,.433,.08,.36,'','windowhit',()=>travel(4))];
if(group==='eratosthenes')return [
region('2',.25,.5,.04,.08,'Comincio dal 2 e cancello i suoi multipli maggiori di 2.'),
region('3',.40,.5,.04,.08,'Il primo numero non cancellato dopo il 2 è il 3. Cancello i suoi multipli maggiori di 3.'),
region('5',.60,.5,.04,.08,'Proseguo con il primo numero non cancellato, senza cancellare il numero stesso.'),
region('√',.75,.5,.04,.08,'Per trovare i primi fino a N basta eliminare i multipli dei primi non superiori a √N.')];
return divisorRegions();
}
function divisorRegions(){
const rows=[
[20,270,530,190,152,'Sono 20: sono multiplo di 2, 4, 5 e 10, e anche di 1 e 20.'],
[6,483,529,115,142,'Sono 6: sono divisore di 12 e multiplo di 2 e 3. Infatti 12 = 6 × 2 e 6 = 2 × 3.'],
[12,684,527,153,141,'Sono 12: sono multiplo di 3 e 4. I miei divisori positivi sono 1, 2, 3, 4, 6 e 12.'],
[15,892,529,151,136,'Sono 15: sono multiplo di 3 e 5. Infatti 15 = 3 × 5.'],
[24,1127,531,185,140,'Sono 24: sono multiplo di 6, 8 e 12. Sono anche divisore di 48.'],
[1,1340,528,94,145,'Sono 1: sono divisore di ogni numero naturale positivo. Non sono né primo né composto.'],
[9,1551,529,117,147,'Sono 9: sono multiplo di 3 e divisore di 18, 27 e 36.']];
return rows.map(([n,x,y,w,h,text])=>region(n,x/1774,y/887,w/1774,h/887,text));}

class Pano{
constructor(node,file){
this.node=node;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(72,node.clientWidth/node.clientHeight,1,1100);
this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.outputEncoding=THREE.sRGBEncoding;this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.setSize(node.clientWidth,node.clientHeight);node.append(this.renderer.domElement);
this.lon=180;this.lat=0;this.fov=72;this.markerObjects=[];this.listeners=[];
const geo=new THREE.SphereGeometry(500,96,64);geo.scale(-1,1,1);this.mat=new THREE.MeshBasicMaterial({color:0xffffff});this.sphere=new THREE.Mesh(geo,this.mat);this.scene.add(this.sphere);
new THREE.TextureLoader().load(A+file,tex=>{if(this.dead){tex.dispose();return}tex.encoding=THREE.sRGBEncoding;this.mat.map=tex;this.mat.needsUpdate=true},undefined,()=>{if(!this.dead)this.node.insertAdjacentHTML('beforeend','<p class="pano-hint">Immagine panoramica non caricata.</p>')});
this.bubble=el('div','pano-bubble hide');this.bubble.setAttribute('role','status');this.bubble.append(btn('×',()=>this.closeBubble(),'bubble-close'),this.bubbleText=el('p'));node.append(this.bubble);this.install();this.tick();
}
listen(n,e,f,o){n.addEventListener(e,f,o);this.listeners.push([n,e,f,o])}
closeBubble(){this.active=null;this.bubble.classList.add('hide')}
install(){const c=this.node;let start=null,old=null;this.moved=false;
this.listen(c,'pointerdown',e=>{if(e.target.closest('.pano-controls,.pano-bubble'))return;start=old=[e.clientX,e.clientY];this.moved=false;this.drag=true;});
this.listen(c,'pointermove',e=>{if(!this.drag||!old)return;const dx=e.clientX-old[0],dy=e.clientY-old[1];if(Math.hypot(e.clientX-start[0],e.clientY-start[1])>7)this.moved=true;if(this.moved){this.lon-=dx*.13;this.lat=Math.max(-60,Math.min(60,this.lat+dy*.13));c.classList.add('dragging')}old=[e.clientX,e.clientY]});
const stop=()=>{this.drag=false;old=null;c.classList.remove('dragging')};this.listen(window,'pointerup',stop);this.listen(window,'pointercancel',stop);
this.listen(c,'click',e=>{if(this.moved){e.stopPropagation();e.preventDefault();return}if(!e.target.closest('button,.pano-bubble'))this.closeBubble()},true);
this.listen(c,'wheel',e=>{e.preventDefault();this.zoom(e.deltaY*.05)},{passive:false});
this.ro=new ResizeObserver(()=>{if(this.dead)return;const w=c.clientWidth,h=c.clientHeight;if(w&&h){this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h)}});this.ro.observe(c);
}
markers(items){this.markerObjects=items.map(item=>{const b=btn('',()=>{if(item.action){item.action();return}this.active=item;this.bubbleText.textContent=item.text;this.bubble.classList.remove('hide')},'pano-marker '+item.type);b.setAttribute('aria-label','Esplora: '+item.label);this.node.append(b);return {item,b}})}
project(u,v){const t=u*Math.PI*2,p=v*Math.PI;const vec=new THREE.Vector3(490*Math.sin(p)*Math.cos(t),490*Math.cos(p),490*Math.sin(p)*Math.sin(t));if(vec.clone().applyMatrix4(this.camera.matrixWorldInverse).z>=-1)return null;vec.project(this.camera);return {x:(vec.x+1)*this.node.clientWidth/2,y:(1-vec.y)*this.node.clientHeight/2}}
tick(){if(this.dead)return;const phi=THREE.MathUtils.degToRad(90-this.lat),theta=THREE.MathUtils.degToRad(this.lon);this.camera.lookAt(new THREE.Vector3(500*Math.sin(phi)*Math.cos(theta),500*Math.cos(phi),500*Math.sin(phi)*Math.sin(theta)));this.camera.updateMatrixWorld();const w=this.node.clientWidth,h=this.node.clientHeight;
for(const {item,b} of this.markerObjects){const q=this.project(item.u,item.v);const corners=[[-1,-1],[1,-1],[-1,1],[1,1]].map(([x,y])=>this.project(item.u+x*item.uw/2,item.v+y*item.vh/2));if(!q||corners.some(c=>!c)||q.x< -100||q.x>w+100||q.y< -100||q.y>h+100){b.style.display='none';continue}const xs=corners.map(c=>c.x),ys=corners.map(c=>c.y);const bw=Math.max(44,Math.max(...xs)-Math.min(...xs)),bh=Math.max(44,Math.max(...ys)-Math.min(...ys));b.style.cssText=`display:block;left:${q.x}px;top:${q.y}px;width:${bw}px;height:${bh}px`;
}
if(this.active){const q=this.project(this.active.u,this.active.v-this.active.vh/2);if(!q||q.x<0||q.x>w||q.y<0||q.y>h)this.bubble.style.visibility='hidden';else{this.bubble.style.visibility='visible';const bw=this.bubble.offsetWidth,bh=this.bubble.offsetHeight;this.bubble.style.left=Math.max(8,Math.min(w-bw-8,q.x-bw/2))+'px';this.bubble.style.top=Math.max(64,Math.min(h-bh-110,q.y-bh-12))+'px';}}
this.renderer.render(this.scene,this.camera);this.raf=requestAnimationFrame(()=>this.tick());
}
zoom(d){this.fov=Math.max(32,Math.min(98,this.fov+d));this.camera.fov=this.fov;this.camera.updateProjectionMatrix()}
dispose(){this.dead=true;cancelAnimationFrame(this.raf);this.ro?.disconnect();this.listeners.forEach(([n,e,f,o])=>n.removeEventListener(e,f,o));this.mat.map?.dispose();this.mat.dispose();this.sphere.geometry.dispose();this.renderer.dispose();this.renderer.domElement.remove()}
}
function renderPanoScene(s){const node=el('div','pano');stage.append(node);if(!window.THREE){node.innerHTML=`<div class="scene" style="background-image:url('${A+s.bg}')"><div class="intro"><h2>Impossibile caricare il visore 360°</h2><p>Serve la libreria Three.js e una connessione a Internet.</p></div></div>`;return}viewer=new Pano(node,s.bg);const hint=el('div','pano-hint','Trascina per esplorare · clicca direttamente sui numeri · scorri per zoomare');node.append(hint);setTimeout(()=>hint.remove(),7000);
const markers=makeMarkers(s.group);viewer.markers(markers);const controls=el('div','pano-controls');node.append(controls);controls.append(btn('＋',()=>viewer.zoom(-10),'mini'),btn('−',()=>viewer.zoom(10),'mini'),btn('Mostra curiosità',e=>{node.classList.toggle('show-hotspots');},'mini'));
if(s.group==='primes')viewer.lon=120;
if(s.group==='euclid')viewer.lon=220;
if(s.group==='eratosthenes'){controls.append(btn('▶ Video Eratostene',()=>playVideo('video4'),'mini'));if(C.video5)controls.append(btn('▶ Secondo video',()=>playVideo('video5'),'mini'))}
if(s.quiz){controls.append(btn(quizPassed[index]?'✓ Quiz superato · prosegui':'✦ Affronta 5 quesiti',()=>quizPassed[index]?travel(index+1):startQuiz(s.quiz,5,3,()=>{quizPassed[index]=true;travel(index+1)}),'btn'));}else if(s.group==='euclid'){hint.textContent='Esplora la biblioteca: una finestra nasconde il passaggio per Arsinoe.';}else if(s.group==='eratosthenes'){controls.append(btn('➜ Entra nel crivello interattivo',()=>travel(6),'btn'));}else controls.append(btn('✧ Prosegui',()=>travel(index+1),'btn'));
}
function renderEmbed(){let root=el('div','scene');root.innerHTML=`<div class="intro" style="top:63px;max-width:none"><h2>Il crivello di Eratostene</h2><p>Sperimenta: quali numeri restano quando elimini progressivamente i multipli?</p></div><iframe id="crivello" class="embed embedScene" title="Crivello Matica" loading="eager" src="${escapeH(C.crivello)}"></iframe>`;let bar=el('div','embedToolbar');bar.append(btn('Apri in un’altra scheda',()=>window.open(C.crivello,'_blank','noopener'),'btn alt'));bar.append(btn('✧ Ho esplorato il crivello · prosegui',()=>travel(index+1)));root.append(bar);stage.append(root)}
function createPrimeQuiz(){const nums=shuffle(Array.from({length:30},(_,i)=>i+1));let selected=nums.slice(0,5);if(!selected.includes(1)&&Math.random()<.5)selected[0]=1;return selected.map((n,i)=>{if(n===1||prime(n)||i%2===0)return {type:'choice',text:`Il numero ${n} è…`,choices:['Primo','Composto','Né primo né composto'],correct:n===1?2:prime(n)?0:1,explanation:n===1?'1 ha un solo divisore positivo.':prime(n)?`${n} ha esattamente due divisori positivi.`:`${n} = ${factor(n).join(' × ')}.`};return {type:'factors',text:`Scomponi ${n} in fattori primi. Scrivi per esempio 2×3×3.`,n,explanation:`${n} = ${factor(n).join(' × ')}. L’ordine dei fattori non conta.`}})}
function createDivQuiz(){const pool=[];for(let a=2;a<=12;a++)for(let b=2;b<=12;b++){pool.push({type:'choice',text:`${a} è divisore di ${a*b}?`,choices:['Sì','No'],correct:0,explanation:`${a*b} = ${a} × ${b}.`});pool.push({type:'choice',text:`${a*b} è multiplo di ${a}?`,choices:['Sì','No'],correct:0,explanation:`${a*b} = ${a} × ${b}.`});let n=a*b+1;pool.push({type:'choice',text:`${a} è divisore di ${n}?`,choices:['Sì','No'],correct:1,explanation:`${n} diviso ${a} non dà un quoziente intero.`})}return shuffle(pool).slice(0,5)}
// Bank of 50+ independently constructed, editable questions; options randomized at runtime.
function finalBank(){let q=[
['Quale definizione descrive un numero primo?',['Un naturale maggiore di 1 con esattamente due divisori positivi','Un numero divisibile per 1 e per 2','Un naturale con un solo divisore'],0,'La definizione richiede esattamente due divisori: 1 e se stesso.'],
['Il numero 1 è…',['Primo','Composto','Né primo né composto'],2,'1 possiede un unico divisore positivo.'],
['Qual è l’unico numero primo pari?',['2','4','6'],0,'Ogni numero pari maggiore di 2 è divisibile anche per 2.'],
['Quale enunciato esprime il Teorema fondamentale dell’aritmetica?',['Ogni naturale maggiore di 1 è primo oppure si scrive come prodotto di primi, in modo unico a meno dell’ordine','Ogni naturale è somma di due primi','Ogni numero primo è pari'],0,'La scomposizione in primi esiste ed è unica, salvo l’ordine dei fattori.'],
['Quanti numeri primi esistono?',['Infiniti','Esattamente cento','Un numero finito ancora sconosciuto'],0,'Euclide dimostrò che non può esistere un elenco completo e finito di tutti i primi.'],
['Nel crivello di Eratostene, dopo aver considerato il 2…',['Elimino i suoi multipli maggiori di 2','Elimino il 2','Elimino tutti i dispari'],0,'Il 2 deve restare: è un numero primo.'],
['Se a è divisore di b, allora…',['b è multiplo di a','a è necessariamente maggiore di b','b è sempre primo'],0,'La relazione tra divisore e multiplo è reciproca.'],
['Quale affermazione è corretta?',['Ogni naturale positivo è multiplo di 1','1 è primo','Ogni dispari è primo'],0,'Qualunque n è 1 × n.'],
['Un numero composto maggiore di 1 è…',['Un numero con più di due divisori positivi','Un numero dispari','Un numero che termina in 0'],0,'I composti possiedono altri divisori oltre a 1 e a se stessi.']
].map(([text,choices,correct,explanation])=>({type:'choice',text,choices,correct,explanation}));
for(let n of [4,6,8,9,10,12,14,15,16,18,20,21,24,25,27,28,30,32,36,40,42,45,48,49,50,54,60,63,70,72,75,81,84,90,96,100])q.push({type:'factors',text:`Scomponi ${n} in fattori primi.`,n,explanation:`${n} = ${factor(n).join(' × ')}.`});
for(let n of [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,51,57,61,67,71,77,79,83,89,91,97])q.push({type:'choice',text:`Il numero ${n} è primo o composto?`,choices:['Primo','Composto'],correct:prime(n)?0:1,explanation:prime(n)?`${n} è primo.`:`${n} = ${factor(n).join(' × ')}.`});
for(let [a,b] of [[2,18],[3,21],[4,28],[5,45],[6,42],[7,49],[8,72],[9,81],[10,100],[11,99],[12,108],[4,30],[5,32],[7,48],[9,50],[8,54]])q.push({type:'choice',text:`${a} è divisore di ${b}?`,choices:['Sì','No'],correct:b%a===0?0:1,explanation:b%a===0?`${b} = ${a} × ${b/a}.`:`La divisione di ${b} per ${a} non è esatta.`});
for(let [a,b] of [[18,3],[25,5],[40,10],[48,6],[64,8],[72,9],[81,3],[84,7],[91,13],[50,6],[33,5],[42,8]])q.push({type:'choice',text:`${a} è multiplo di ${b}?`,choices:['Sì','No'],correct:a%b===0?0:1,explanation:a%b===0?`${a} = ${b} × ${a/b}.`:`${a} diviso ${b} non è un intero.`});return q;}
function finalQuestions(){let bank=shuffle(finalBank()),out=[];for(let typ of ['factors','choice']){let take=bank.filter(q=>q.type===typ).slice(0,typ==='factors'?5:10);out.push(...take)}return shuffle(out).map(q=>q.type!=='choice'?q:(()=>{let c=shuffle(q.choices.map((v,i)=>({v,good:i===q.correct})));return {...q,choices:c.map(x=>x.v),correct:c.findIndex(x=>x.good)}})())}
function startQuiz(type,total,threshold,success){const qs=type==='prime'?createPrimeQuiz():type==='divisor'?createDivQuiz():finalQuestions();questionState={qs:qs.slice(0,total),i:0,score:0,answered:false,threshold,success,type};renderQ()}
function checkAnswer(q,value){if(q.type==='factors'){const ar=normFactors(value);return ar.length===factor(q.n).length&&ar.every((x,i)=>x===factor(q.n)[i])}return Number(value)===q.correct}
function renderQ(){let S=questionState;if(!S)return;if(S.i>=S.qs.length)return endQuiz();const q=S.qs[S.i];let html=`<div class="qcard"><div class="qcount">Domanda ${S.i+1}/${S.qs.length} · Risposte corrette: ${S.score}</div><h2>${escapeH(q.text)}</h2><div id="qAnswers" class="answers">${q.type==='factors'?'<input id="factorAnswer" type="text" aria-label="Scomposizione in fattori primi" placeholder="es. 2 × 2 × 3" autocomplete="off">':q.choices.map((c,i)=>`<button class="answer" data-choice="${i}">${escapeH(c)}</button>`).join('')}</div><p id="feedback" class="feedback" aria-live="polite">Ragiona con calma. Ogni domanda vale un punto.</p><button id="check" class="btn" disabled>Conferma risposta</button><button id="nextQ" class="btn alt hide">${S.i+1===S.qs.length?'Vedi risultato':'Domanda successiva →'}</button></div>`;modal(html);let choice=null;$('#qAnswers').querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{choice=Number(b.dataset.choice);$('#qAnswers').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));$('#check').disabled=false});if(q.type==='factors'){const input=$('#factorAnswer');input.addEventListener('input',()=>$('#check').disabled=!input.value.trim());input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!$('#check').disabled)$('#check').click()})}
$('#check').onclick=()=>{let val=q.type==='factors'?$('#factorAnswer').value:choice;let correct=checkAnswer(q,val);if(correct)S.score++;$('#feedback').textContent=(correct?'✓ Risposta corretta. ':'✕ Non esatta. ')+q.explanation;$('#qAnswers').querySelectorAll('button,input').forEach(b=>b.disabled=true);$('#check').classList.add('hide');$('#nextQ').classList.remove('hide');$('#closeModal').disabled=true;};$('#nextQ').onclick=()=>{S.i++;hideModal();$('#closeModal').disabled=false;renderQ()}}
function endQuiz(){const s=questionState;$('#closeModal').disabled=false;let passed=s.score>=s.threshold;modal(`<div class="qcard"><h2>${passed?'✦ Portale sbloccato!':'✧ Puoi riprovare'}</h2><p>Hai ottenuto <strong>${s.score}/${s.qs.length}</strong>. Soglia richiesta: <strong>${s.threshold}/${s.qs.length}</strong>.</p><p>${passed?'Il tuo viaggio può continuare.':'Torna a esplorare, poi ritenta: saranno estratte nuove domande.'}</p><button id="quizDone" class="btn">${passed?'Prosegui →':'Torna alla stanza'}</button></div>`);$('#quizDone').onclick=()=>{hideModal();questionState=null;if(passed)s.success()};}
function renderFinal(){let root=el('div','scene');root.style.backgroundImage=`url('${A}atrio-primi.png')`;root.innerHTML='<div class="intro"><h1>Il portale della conoscenza</h1><p>Hai esplorato il mondo dei numeri primi, incontrato Euclide, sperimentato il crivello e imparato le relazioni tra multipli e divisori.</p><p><b>Prova conclusiva:</b> 15 quesiti casuali, uno alla volta. Con almeno 9 punti ricevi l’attestato.</p></div>';const wrap=el('div','portal-wrap');wrap.append(btn('✦ Inizia la prova finale (15 domande)',()=>startQuiz('final',15,9,()=>{hideModal();showCert(questionState?.score??lastFinalScore)})));root.append(wrap);stage.append(root);}
let lastFinalScore=0; // Used to preserve the result once the quiz modal closes.
// Patch: keep final score before invoking certificate callback, with an explicit score argument.
const originalEnd=endQuiz;
endQuiz=function(){let s=questionState;if(s?.type==='final')lastFinalScore=s.score;originalEnd()};
function showCert(score){score=Number.isInteger(score)?score:lastFinalScore;if(score<9){render();return}let level=score===15?'ECCELLENTE':score>=13?'OTTIMO':score>=11?'BUONO':'BASE';stage.innerHTML=`<div id="finish"><div class="certwrap"><div class="certificate"><div style="font-size:28px">✦ MATICA ✦</div><h1>Attestato del viaggio<br>dei numeri primi</h1><p>Si conferisce a</p><input id="studentName" maxlength="65" placeholder="Inserisci il tuo nome" aria-label="Nome dello studente"><h2>${level}</h2><p>per aver completato il percorso interattivo e superato la prova finale con</p><div style="font-size:42px;font-weight:bold">${score} / 15</div><p>Con Mate e Carl • Il viaggio nella matematica</p><small>© Claudia Bartoli — attestato di completamento del percorso didattico</small></div><div class="certButtons"><button id="printCert" class="btn">Stampa / Salva PDF</button><button id="retryFinal" class="btn alt">Riprova il test</button></div></div></div>`;$('#printCert').onclick=()=>{if(!$('#studentName').value.trim()){alert('Inserisci prima il tuo nome.');$('#studentName').focus();return}window.print()};$('#retryFinal').onclick=()=>{index=9;render()}}
$('#privacyBtn').onclick=()=>modal(`<h2>Privacy</h2><p>Questo progetto didattico non richiede registrazione, non dispone di un backend proprietario e non invia al gestore i risultati dei quiz o il nome inserito nell’attestato.</p><p>I video incorporati da YouTube (modalità youtube-nocookie), l’eventuale libreria Three.js caricata da CDN e la risorsa esterna del crivello possono effettuare connessioni ai rispettivi servizi, soggetti alle loro informative. Prima di incorporare il crivello verificare anche la relativa informativa.</p><p>Per informazioni: <a href="mailto:${escapeH(C.email)}">${escapeH(C.email)}</a>.</p><p>© Claudia Bartoli. Riproduzione e distribuzione dei materiali protetti non autorizzate, salvo eccezioni previste dalla legge e diritti di terzi.</p>`);
$('#helpBtn').onclick=()=>modal('<h2>Come si gioca</h2><p>1. In ciascun atrio premi il cerchio per aprire la videolezione. Quando chiudi il video, il cerchio diventa un portale verso la scena successiva.</p><p>2. Nei panorami trascina per guardarti attorno e clicca sui numeri o sui simboli luminosi. Su smartphone trascina con un dito.</p><p>3. Supera i due mini quiz con almeno 3 risposte esatte su 5. Nel crivello esplora la risorsa e premi Prosegui.</p><p>4. Rispondi a 15 quesiti finali: per ottenere l’attestato servono almeno 9 punti.</p><p>Le scomposizioni si scrivono ad esempio 2×2×3; l’ordine dei fattori non conta.</p>');
$('#restartBtn').onclick=()=>{if(confirm('Vuoi ricominciare il viaggio dall’inizio?')){if(viewer){viewer.dispose();viewer=null}index=0;watched={};quizPassed={};visited.clear();hideModal();render()}};
$('#audioBtn').onclick=()=>modal('<p>La colonna sonora non è inclusa in questa versione. Le videolezioni conservano i propri controlli audio.</p>');
render();
})();
